# WARNING: Do not deploy this tutorial configuration directly to a production environment
#
# The tutorial docker-compose files have not been written for production deployment and will not 
# scale. A proper architecture has been sacrificed to keep the narrative focused on the learning 
# goals, they are just used to deploy everything onto a single Docker machine. All FIWARE components 
# are running at full debug and extra ports have been exposed to allow for direct calls to services. 
# They also contain various obvious security flaws - passwords in plain text, no load balancing,
# no use of HTTPS and so on. 
# 
# This is all to avoid the need of multiple machines, generating certificates, encrypting secrets
# and so on, purely so that a single docker-compose file can be read as an example to build on, 
# not use directly. 
# 
# When deploying to a production environment, please looking at the SmartSDK Recipes
# in order to scale up to a proper architecture:
# 
# see: https://smartsdk.github.io/smartsdk-recipes/
#

version: '3.7'

services:
    # context broker service
    orion:
      image: fiware/orion:2.4.0
      hostname: orion
      container_name: fiware-orion
      depends_on:
        - mongo-db
      networks:
        - default
      expose:
        - "1026"
      ports:
        - "1026:1026" # localhost:1026
      command: -dbhost mongo-db -logLevel DEBUG
      entrypoint: ["/usr/bin/contextBroker","-fg", "-multiservice", "-ngsiv1Autocast", "-corsOrigin='__ALL'", "-httpTimeout='1000'" ]
      healthcheck:
        test: curl --fail -s http://orion:1026/version || exit 1
  
  # Database
    mongo-db:
      image: mongo:3.6
      hostname: mongo-db
      container_name: db-mongo
      expose:
        - "27017"
      ports:
        - "27017:27017" # localhost:27017
      networks:
        - default
      command: --bind_ip_all --smallfiles
      volumes:
        - mongo-db:/data
  
  # eth service
    eth-service:
      build: ./EthService
      container_name: eth-service
      hostname: eth-service
      ports:
        - 3002:3002
      environment:
        - PORT=3002 # http://localhost:3002
        - RPC_URL= http://ganache:8545 # http://localhost:8545
        - CONTEXT_BROKER= http://orion:1026
      depends_on:
        - ganache
      links:
        - ganache:ganache
      networks: 
        - default
  
  # json-rpc client
    ganache:
        build: ./ganache
        container_name: ganache
        hostname: ganache
        ports:
          - 8545:8545
        networks:
        - default
        
#  volumes 
volumes:
  mongo-db: ~
  
# network
networks:
  default:
    ipam:
      config:
        - subnet: 172.19.1.0/24