site_name: Taurus
site_url: https://taurus.readthedocs.io
repo_url: https://github.com/fiware-blockchain/Taurus/docs
site_description: Taurus Documentation
docs_dir: docs
site_dir: html
edit_uri: edit/master/docs/
markdown_extensions: [toc, fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css:
  [
    "https://www.fiware.org/style/fiware_readthedocs.css",
    "https://www.fiware.org/style/fiware_readthedocs_iot.css",
  ]
# google_analytics: ["", ""]
pages:
  - Home: index.md
  - "Usage": usage.md
  - "APIs": apis.md
  - "Installation": installation.md
