version: '2'
services:
  taurus:
      build:
        context: https://github.com/FIWARE-Blockchain/Taurus.git
      container_name: fiware-taurus
      hostname: taurus  
      ports:
        - '4001:4001'
      environment: 
        - TAURUS_PORT=4001
        - ETHEREUM_URL=localhost
        - ETHEREUM_PORT=30303
        - ORION_URL=localhost
        - ORION_PORT=1026
        - THREADS=10
      healthcheck:
        interval: 5s
  
  mongo:
     image: mongo:4.4
     command: --nojournal
  orion:
     image: fiware/orion-ld:0.7.0
     links:
       - mongo
     ports:
       - "1026:1026"
     command: -dbhost mongo

   #DLT
  ethreum:
      build:
        context: https://github.com/ethereum/go-ethereum.git
      container_name: ethereum-goethereum
      hostname: ethereum
      ports:
        - '30303:30303'