# Generated by Django 3.1.3 on 2020-12-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractAddress', models.CharField(max_length=255)),
                ('eventSpecification', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('abi', models.CharField(max_length=255)),
                ('interval', models.IntegerField())
            ],
        ),
    ]
